"""add chat conversation message tables

Revision ID: 2d2814d023b5
Revises: 6b8e2a4d9c31
Create Date: 2026-07-24 20:33:43.356810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2d2814d023b5"
down_revision: Union[str, None] = "6b8e2a4d9c31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_conversations",
        sa.Column("conversation_id", sa.String(length=64), nullable=False, comment="Public conversation UUID"),
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="Owner user ID"),
        sa.Column("title", sa.String(length=200), nullable=True, comment="Conversation title"),
        sa.Column("capability", sa.String(length=50), nullable=False, comment="Primary capability"),
        sa.Column("execution_engine", sa.String(length=30), nullable=False, comment="Execution engine"),
        sa.Column(
            "rag_enabled", sa.Boolean(), server_default="false", nullable=False, comment="Whether RAG is enabled"
        ),
        sa.Column(
            "tool_enabled",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether tool calling is enabled",
        ),
        sa.Column("model_config_id", sa.BigInteger(), nullable=False, comment="User AI model config ID"),
        sa.Column("model_name", sa.String(length=100), nullable=True, comment="Last actual model name"),
        sa.Column("agent_config_id", sa.BigInteger(), nullable=True, comment="Reserved agent or graph config ID"),
        sa.Column("message_count", sa.Integer(), server_default="0", nullable=False, comment="Message count"),
        sa.Column("total_input_tokens", sa.Integer(), server_default="0", nullable=False, comment="Input token total"),
        sa.Column(
            "total_output_tokens", sa.Integer(), server_default="0", nullable=False, comment="Output token total"
        ),
        sa.Column("total_tokens", sa.Integer(), server_default="0", nullable=False, comment="Token total"),
        sa.Column("last_message_at", sa.DateTime(), nullable=True, comment="Last message time"),
        sa.Column("extra_metadata", sa.JSON(), nullable=True, comment="Extension metadata"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_config_id"],
            ["user_ai_model_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chat_conversations_user_deleted_last",
        "chat_conversations",
        ["user_id", "deleted_at", "last_message_at"],
        unique=False,
    )
    op.create_index(op.f("ix_chat_conversations_capability"), "chat_conversations", ["capability"], unique=False)
    op.create_index(
        op.f("ix_chat_conversations_conversation_id"), "chat_conversations", ["conversation_id"], unique=True
    )
    op.create_index(op.f("ix_chat_conversations_deleted_at"), "chat_conversations", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_chat_conversations_last_message_at"), "chat_conversations", ["last_message_at"], unique=False
    )
    op.create_index(
        op.f("ix_chat_conversations_model_config_id"), "chat_conversations", ["model_config_id"], unique=False
    )
    op.create_index(op.f("ix_chat_conversations_user_id"), "chat_conversations", ["user_id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("message_id", sa.String(length=64), nullable=False, comment="Public message UUID"),
        sa.Column("conversation_db_id", sa.BigInteger(), nullable=False, comment="Conversation database ID"),
        sa.Column("role", sa.String(length=20), nullable=False, comment="system/user/assistant/tool"),
        sa.Column("content", sa.Text(), nullable=False, comment="Message content"),
        sa.Column("message_index", sa.Integer(), nullable=False, comment="Message order in conversation"),
        sa.Column("capability", sa.String(length=50), nullable=True, comment="Primary capability used by this turn"),
        sa.Column("capabilities", sa.JSON(), nullable=True, comment="Capability set used by this turn"),
        sa.Column(
            "execution_engine", sa.String(length=30), nullable=True, comment="Execution engine used by this turn"
        ),
        sa.Column(
            "rag_enabled", sa.Boolean(), server_default="false", nullable=False, comment="Whether RAG was enabled"
        ),
        sa.Column(
            "tool_enabled",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether tool calling was enabled",
        ),
        sa.Column("status", sa.String(length=20), server_default="completed", nullable=False, comment="Message status"),
        sa.Column(
            "model_config_id", sa.BigInteger(), nullable=True, comment="User AI model config ID used by this turn"
        ),
        sa.Column("model_name", sa.String(length=100), nullable=True, comment="Actual model name"),
        sa.Column("input_tokens", sa.Integer(), nullable=True, comment="Input tokens"),
        sa.Column("output_tokens", sa.Integer(), nullable=True, comment="Output tokens"),
        sa.Column("total_tokens", sa.Integer(), nullable=True, comment="Total tokens"),
        sa.Column("finish_reason", sa.String(length=50), nullable=True, comment="LLM finish reason"),
        sa.Column("tool_calls", sa.JSON(), nullable=True, comment="Assistant tool call payloads"),
        sa.Column("tool_call_id", sa.String(length=100), nullable=True, comment="Tool call ID for tool messages"),
        sa.Column("citations", sa.JSON(), nullable=True, comment="RAG citations"),
        sa.Column("extra_metadata", sa.JSON(), nullable=True, comment="Extension metadata"),
        sa.Column("error_message", sa.Text(), nullable=True, comment="Error message"),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["conversation_db_id"], ["chat_conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["model_config_id"],
            ["user_ai_model_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chat_messages_conversation_index", "chat_messages", ["conversation_db_id", "message_index"], unique=True
    )
    op.create_index(op.f("ix_chat_messages_capability"), "chat_messages", ["capability"], unique=False)
    op.create_index(op.f("ix_chat_messages_conversation_db_id"), "chat_messages", ["conversation_db_id"], unique=False)
    op.create_index("ix_chat_messages_created_at", "chat_messages", ["created_at"], unique=False)
    op.create_index(op.f("ix_chat_messages_message_id"), "chat_messages", ["message_id"], unique=True)
    op.create_index(op.f("ix_chat_messages_model_config_id"), "chat_messages", ["model_config_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_messages_model_config_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_message_id"), table_name="chat_messages")
    op.drop_index("ix_chat_messages_created_at", table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_conversation_db_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_capability"), table_name="chat_messages")
    op.drop_index("idx_chat_messages_conversation_index", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_chat_conversations_user_id"), table_name="chat_conversations")
    op.drop_index(op.f("ix_chat_conversations_model_config_id"), table_name="chat_conversations")
    op.drop_index(op.f("ix_chat_conversations_last_message_at"), table_name="chat_conversations")
    op.drop_index(op.f("ix_chat_conversations_deleted_at"), table_name="chat_conversations")
    op.drop_index(op.f("ix_chat_conversations_conversation_id"), table_name="chat_conversations")
    op.drop_index(op.f("ix_chat_conversations_capability"), table_name="chat_conversations")
    op.drop_index("idx_chat_conversations_user_deleted_last", table_name="chat_conversations")
    op.drop_table("chat_conversations")
    # ### end Alembic commands ###
