"""add_type_to_telegraph

Revision ID: 40cf1c24ffdd
Revises: 915e431eb823
Create Date: 2026-06-03 17:49:00.736358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "40cf1c24ffdd"
down_revision: Union[str, None] = "915e431eb823"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("telegraph_list", sa.Column("type", sa.String(length=20), nullable=True))
    op.create_index(op.f("ix_telegraph_list_type"), "telegraph_list", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telegraph_list_type"), table_name="telegraph_list")
    op.drop_column("telegraph_list", "type")
    # ### end Alembic commands ###
