"""合并开放基金/场内基金历史净值表 删除货币基金申购状态，赎回状态字段

Revision ID: 601e0cb5b7f9
Revises: e4a7c9b1d302
Create Date: 2026-08-15 16:11:41.942711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '601e0cb5b7f9'
down_revision: Union[str, None] = 'e4a7c9b1d302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_open_exchange_nav_history',
    sa.Column('fund_id', sa.BigInteger(), nullable=False),
    sa.Column('fund_code', sa.String(length=20), nullable=False, comment='基金代码'),
    sa.Column('data_date', sa.Date(), nullable=False, comment='净值日期'),
    sa.Column('unit_nav', sa.Numeric(precision=18, scale=8), nullable=True, comment='单位净值'),
    sa.Column('accumulated_nav', sa.Numeric(precision=18, scale=8), nullable=True, comment='累计净值'),
    sa.Column('daily_growth_pct', sa.Numeric(precision=12, scale=6), nullable=True, comment='日增长率(%)'),
    sa.Column('fetched_at', sa.DateTime(), nullable=False, comment='抓取时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'data_date', name='uq_fund_open_exchange_nav_history_fund_date')
    )
    op.create_index(op.f('ix_fund_open_exchange_nav_history_data_date'), 'fund_open_exchange_nav_history', ['data_date'], unique=False)
    op.create_index(op.f('ix_fund_open_exchange_nav_history_deleted_at'), 'fund_open_exchange_nav_history', ['deleted_at'], unique=False)
    op.drop_index('ix_fund_exchange_nav_history_data_date', table_name='fund_exchange_nav_history')
    op.drop_index('ix_fund_exchange_nav_history_deleted_at', table_name='fund_exchange_nav_history')
    op.drop_table('fund_exchange_nav_history')
    op.drop_index('ix_fund_open_nav_history_data_date', table_name='fund_open_nav_history')
    op.drop_index('ix_fund_open_nav_history_deleted_at', table_name='fund_open_nav_history')
    op.drop_table('fund_open_nav_history')
    op.drop_column('fund_money_yield_history', 'purchase_status')
    op.drop_column('fund_money_yield_history', 'redemption_status')
    op.alter_column('fund_performance_trend_latest', 'series_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='ECharts 可直接消费的完整曲线数组',
               existing_comment='完整曲线数组',
               existing_nullable=False)
    op.alter_column('fund_performance_trend_latest', 'schema_version',
               existing_type=sa.SMALLINT(),
               comment='series_data 结构版本',
               existing_comment='JSON结构版本',
               existing_nullable=False,
               existing_server_default=sa.text("'1'::smallint"))
    op.alter_column('fund_performance_trend_latest', 'point_count',
               existing_type=sa.INTEGER(),
               comment='全部曲线的点数合计',
               existing_comment='全部曲线点数合计',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fund_performance_trend_latest', 'point_count',
               existing_type=sa.INTEGER(),
               comment='全部曲线点数合计',
               existing_comment='全部曲线的点数合计',
               existing_nullable=False)
    op.alter_column('fund_performance_trend_latest', 'schema_version',
               existing_type=sa.SMALLINT(),
               comment='JSON结构版本',
               existing_comment='series_data 结构版本',
               existing_nullable=False,
               existing_server_default=sa.text("'1'::smallint"))
    op.alter_column('fund_performance_trend_latest', 'series_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='完整曲线数组',
               existing_comment='ECharts 可直接消费的完整曲线数组',
               existing_nullable=False)
    op.add_column('fund_money_yield_history', sa.Column('redemption_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='赎回状态'))
    op.add_column('fund_money_yield_history', sa.Column('purchase_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='申购状态'))
    op.create_table('fund_open_nav_history',
    sa.Column('fund_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('fund_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='基金代码'),
    sa.Column('data_date', sa.DATE(), autoincrement=False, nullable=False, comment='净值日期'),
    sa.Column('unit_nav', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True, comment='单位净值'),
    sa.Column('accumulated_nav', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True, comment='累计净值'),
    sa.Column('daily_growth_pct', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=True, comment='日增长率(%)'),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='抓取时间'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name='fund_open_nav_history_fund_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fund_open_nav_history_pkey'),
    sa.UniqueConstraint('fund_id', 'data_date', name='uq_fund_open_nav_history_fund_date')
    )
    op.create_index('ix_fund_open_nav_history_deleted_at', 'fund_open_nav_history', ['deleted_at'], unique=False)
    op.create_index('ix_fund_open_nav_history_data_date', 'fund_open_nav_history', ['data_date'], unique=False)
    op.create_table('fund_exchange_nav_history',
    sa.Column('fund_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('fund_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='基金代码'),
    sa.Column('data_date', sa.DATE(), autoincrement=False, nullable=False, comment='净值日期'),
    sa.Column('unit_nav', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True, comment='单位净值'),
    sa.Column('accumulated_nav', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True, comment='累计净值'),
    sa.Column('daily_growth_pct', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=True, comment='日增长率(%)'),
    sa.Column('purchase_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='申购状态'),
    sa.Column('redemption_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='赎回状态'),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='抓取时间'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name='fund_exchange_nav_history_fund_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fund_exchange_nav_history_pkey'),
    sa.UniqueConstraint('fund_id', 'data_date', name='uq_fund_exchange_nav_history_fund_date')
    )
    op.create_index('ix_fund_exchange_nav_history_deleted_at', 'fund_exchange_nav_history', ['deleted_at'], unique=False)
    op.create_index('ix_fund_exchange_nav_history_data_date', 'fund_exchange_nav_history', ['data_date'], unique=False)
    op.drop_index(op.f('ix_fund_open_exchange_nav_history_deleted_at'), table_name='fund_open_exchange_nav_history')
    op.drop_index(op.f('ix_fund_open_exchange_nav_history_data_date'), table_name='fund_open_exchange_nav_history')
    op.drop_table('fund_open_exchange_nav_history')
    # ### end Alembic commands ###


