"""开放基金新增近5年收益率字段

Revision ID: 71492b50d39d
Revises: 601e0cb5b7f9
Create Date: 2026-08-15 22:27:43.912587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71492b50d39d'
down_revision: Union[str, None] = '601e0cb5b7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_open_rank_latest', sa.Column('return_5y_pct', sa.Numeric(precision=12, scale=6), nullable=True, comment='近5年收益率(%)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund_open_rank_latest', 'return_5y_pct')
    # ### end Alembic commands ###
