"""initial_pg_baseline

Revision ID: 915e431eb823
Revises:
Create Date: 2026-05-29 23:49:12.951612

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "915e431eb823"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
