"""sync_model_and_db_remove_unused_fields_add_comments

Revision ID: bcadacaba706
Revises: e7c9f2d4a1c3
Create Date: 2026-07-07 14:26:53.827891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bcadacaba706"
down_revision: Union[str, None] = "e7c9f2d4a1c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("followed_funds", "cost_price")
    op.drop_column("followed_funds", "hold_units")
    op.alter_column(
        "telegraph_list",
        "is_relevant",
        existing_type=sa.BOOLEAN(),
        comment="是否为金融相关新闻",
        existing_nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "telegraph_list",
        "relevance_score",
        existing_type=sa.INTEGER(),
        comment="相关性评分 0-100",
        existing_nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "telegraph_list",
        "category",
        existing_type=sa.VARCHAR(length=50),
        comment="新闻分类: macro/industry/company/regulatory/international/other",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "telegraph_list",
        "category",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="新闻分类: macro/industry/company/regulatory/international/other",
        existing_nullable=True,
    )
    op.alter_column(
        "telegraph_list",
        "relevance_score",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="相关性评分 0-100",
        existing_nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "telegraph_list",
        "is_relevant",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="是否为金融相关新闻",
        existing_nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.add_column(
        "followed_funds",
        sa.Column(
            "hold_units", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment="持有份额"
        ),
    )
    op.add_column(
        "followed_funds",
        sa.Column(
            "cost_price", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment="持仓成本"
        ),
    )
    # ### end Alembic commands ###
