"""场内基金排行表删除新增成立日期字段

Revision ID: d5be034c0849
Revises: 71492b50d39d
Create Date: 2026-08-15 22:31:13.413813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5be034c0849'
down_revision: Union[str, None] = '71492b50d39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund_exchange_rank_latest', 'inception_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_exchange_rank_latest', sa.Column('inception_date', sa.DATE(), autoincrement=False, nullable=True, comment='成立日期'))
    # ### end Alembic commands ###
