"""add_news_relevance_fields

Revision ID: e7c9f2d4a1c3
Revises: ff8bfb7cce58
Create Date: 2026-06-12

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e7c9f2d4a1c3"
down_revision: Union[str, None] = "ff8bfb7cce58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("telegraph_list", sa.Column("is_relevant", sa.Boolean(), nullable=True, server_default="true"))
    op.add_column("telegraph_list", sa.Column("relevance_score", sa.Integer(), nullable=True, server_default="0"))
    op.add_column("telegraph_list", sa.Column("category", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_telegraph_list_is_relevant"), "telegraph_list", ["is_relevant"], unique=False)
    op.create_index(op.f("ix_telegraph_list_relevance_score"), "telegraph_list", ["relevance_score"], unique=False)
    op.create_index(op.f("ix_telegraph_list_category"), "telegraph_list", ["category"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telegraph_list_category"), table_name="telegraph_list")
    op.drop_index(op.f("ix_telegraph_list_relevance_score"), table_name="telegraph_list")
    op.drop_index(op.f("ix_telegraph_list_is_relevant"), table_name="telegraph_list")
    op.drop_column("telegraph_list", "category")
    op.drop_column("telegraph_list", "relevance_score")
    op.drop_column("telegraph_list", "is_relevant")
    # ### end Alembic commands ###
