"""add_fund_tables

Revision ID: ff8bfb7cce58
Revises: 40cf1c24ffdd
Create Date: 2026-06-09 15:10:57.584326

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ff8bfb7cce58"
down_revision: Union[str, None] = "40cf1c24ffdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followed_funds",
        sa.Column("user_id", sa.BigInteger(), nullable=True, comment="用户ID"),
        sa.Column("fund_code", sa.String(length=20), nullable=False, comment="基金代码"),
        sa.Column("remark", sa.String(length=200), nullable=True, comment="备注"),
        sa.Column("hold_units", sa.Float(), nullable=True, comment="持有份额"),
        sa.Column("cost_price", sa.Float(), nullable=True, comment="持仓成本"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_followed_funds_deleted_at"), "followed_funds", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_followed_funds_fund_code"), "followed_funds", ["fund_code"], unique=False)
    op.create_index(op.f("ix_followed_funds_user_id"), "followed_funds", ["user_id"], unique=False)
    op.create_table(
        "funds",
        sa.Column("code", sa.String(length=20), nullable=False, comment="基金代码"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="基金名称"),
        sa.Column("type", sa.String(length=50), nullable=True, comment="基金类型"),
        sa.Column("nav", sa.Float(), nullable=True, comment="单位净值"),
        sa.Column("acc_nav", sa.Float(), nullable=True, comment="累计净值"),
        sa.Column("day_growth", sa.Float(), nullable=True, comment="日增长率(%)"),
        sa.Column("week_growth", sa.Float(), nullable=True, comment="近一周增长率(%)"),
        sa.Column("month_growth", sa.Float(), nullable=True, comment="近一月增长率(%)"),
        sa.Column("three_month_growth", sa.Float(), nullable=True, comment="近三月增长率(%)"),
        sa.Column("six_month_growth", sa.Float(), nullable=True, comment="近六月增长率(%)"),
        sa.Column("year_growth", sa.Float(), nullable=True, comment="近一年增长率(%)"),
        sa.Column("current_year_growth", sa.Float(), nullable=True, comment="今年以来增长率(%)"),
        sa.Column("manager", sa.String(length=100), nullable=True, comment="基金经理"),
        sa.Column("last_update", sa.DateTime(), nullable=True, comment="最后更新时间"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_funds_code"), "funds", ["code"], unique=True)
    op.create_index(op.f("ix_funds_deleted_at"), "funds", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_funds_name"), "funds", ["name"], unique=False)
    op.create_index(op.f("ix_funds_type"), "funds", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_funds_type"), table_name="funds")
    op.drop_index(op.f("ix_funds_name"), table_name="funds")
    op.drop_index(op.f("ix_funds_deleted_at"), table_name="funds")
    op.drop_index(op.f("ix_funds_code"), table_name="funds")
    op.drop_table("funds")
    op.drop_index(op.f("ix_followed_funds_user_id"), table_name="followed_funds")
    op.drop_index(op.f("ix_followed_funds_fund_code"), table_name="followed_funds")
    op.drop_index(op.f("ix_followed_funds_deleted_at"), table_name="followed_funds")
    op.drop_table("followed_funds")
    # ### end Alembic commands ###
